exclude: /*.css

linters:
  EmptyLineBetweenBlocks:
    enabled: false
  PropertySortOrder:
    enabled: false
  DeclarationOrder:
    enabled: false
  VendorPrefix:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
  MergeableSelector:
    enabled: false
  ImportantRule:
    enabled: false
